name: Dockerized App Deployment
on:
  push:
    branches: [main]
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Deploy using ssh
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ${{ secrets.USERNAME }}
          password: ${{ secrets.PASSWORD }}
          port: 24700
          script: |
            cd FoodDeliverySystem
            git fetch origin
            git checkout main
            git pull origin main
            
            # 1. Build image (BẮT BUỘC có dấu chấm ở cuối)
            docker build -t online-food-app .
            
            # 2. Dọn dẹp container cũ
            docker stop online-food-app || true
            docker rm online-food-app || true
            
            # 3. Chạy container mới
            docker run -d --name online-food-app -p 8080:4000 online-food-app